import { PresetType } from ".";

const Preset: PresetType =
{
    name: "Nivel Zero",
    icon: "minecraft:redstone",
    uncategorized: null,
    "categories": {
        "536ba551-b256-4a68-bbb8-26e42d4f3115": {
            "id": "536ba551-b256-4a68-bbb8-26e42d4f3115",
            "name": "Silos",
            "icon": "minecraft:barrel",
            "items": [
                "minecraft:stone",
                "minecraft:dirt",
                "minecraft:cobblestone",
                "minecraft:sand",
                "minecraft:gravel",
                "minecraft:netherrack"
            ]
        },
        "26b8ca6b-c979-476a-a6e1-76954ef3d95f": {
            "id": "26b8ca6b-c979-476a-a6e1-76954ef3d95f",
            "name": "Nao Stacka",
            "icon": "minecraft:barrier",
            "items": [
                "minecraft:shulker_box",
                "minecraft:white_shulker_box",
                "minecraft:orange_shulker_box",
                "minecraft:magenta_shulker_box",
                "minecraft:light_blue_shulker_box",
                "minecraft:yellow_shulker_box",
                "minecraft:lime_shulker_box",
                "minecraft:pink_shulker_box",
                "minecraft:gray_shulker_box",
                "minecraft:light_gray_shulker_box",
                "minecraft:cyan_shulker_box",
                "minecraft:purple_shulker_box",
                "minecraft:blue_shulker_box",
                "minecraft:brown_shulker_box",
                "minecraft:green_shulker_box",
                "minecraft:red_shulker_box",
                "minecraft:black_shulker_box",
                "minecraft:flint_and_steel",
                "minecraft:bow",
                "minecraft:wooden_sword",
                "minecraft:wooden_shovel",
                "minecraft:wooden_pickaxe",
                "minecraft:wooden_axe",
                "minecraft:wooden_hoe",
                "minecraft:stone_sword",
                "minecraft:stone_shovel",
                "minecraft:stone_pickaxe",
                "minecraft:stone_axe",
                "minecraft:stone_hoe",
                "minecraft:iron_sword",
                "minecraft:iron_shovel",
                "minecraft:iron_pickaxe",
                "minecraft:iron_axe",
                "minecraft:iron_hoe",
                "minecraft:golden_sword",
                "minecraft:golden_shovel",
                "minecraft:golden_pickaxe",
                "minecraft:golden_axe",
                "minecraft:golden_hoe",
                "minecraft:diamond_sword",
                "minecraft:diamond_shovel",
                "minecraft:diamond_pickaxe",
                "minecraft:diamond_axe",
                "minecraft:diamond_hoe",
                "minecraft:leather_helmet",
                "minecraft:leather_chestplate",
                "minecraft:leather_leggings",
                "minecraft:leather_boots",
                "minecraft:chainmail_helmet",
                "minecraft:chainmail_chestplate",
                "minecraft:chainmail_leggings",
                "minecraft:chainmail_boots",
                "minecraft:iron_helmet",
                "minecraft:iron_chestplate",
                "minecraft:iron_leggings",
                "minecraft:iron_boots",
                "minecraft:golden_helmet",
                "minecraft:golden_chestplate",
                "minecraft:golden_leggings",
                "minecraft:golden_boots",
                "minecraft:diamond_helmet",
                "minecraft:diamond_chestplate",
                "minecraft:diamond_leggings",
                "minecraft:diamond_boots",
                "minecraft:mushroom_stew",
                "minecraft:cod_bucket",
                "minecraft:salmon_bucket",
                "minecraft:pufferfish_bucket",
                "minecraft:tropical_fish_bucket",
                "minecraft:minecart",
                "minecraft:chest_minecart",
                "minecraft:furnace_minecart",
                "minecraft:tnt_minecart",
                "minecraft:hopper_minecart",
                "minecraft:saddle",
                "minecraft:oak_boat",
                "minecraft:spruce_boat",
                "minecraft:birch_boat",
                "minecraft:jungle_boat",
                "minecraft:acacia_boat",
                "minecraft:dark_oak_boat",
                "minecraft:milk_bucket",
                "minecraft:writable_book",
                "minecraft:enchanted_book",
                "minecraft:fishing_rod",
                "minecraft:white_bed",
                "minecraft:orange_bed",
                "minecraft:magenta_bed",
                "minecraft:light_blue_bed",
                "minecraft:yellow_bed",
                "minecraft:lime_bed",
                "minecraft:pink_bed",
                "minecraft:gray_bed",
                "minecraft:light_gray_bed",
                "minecraft:cyan_bed",
                "minecraft:purple_bed",
                "minecraft:blue_bed",
                "minecraft:brown_bed",
                "minecraft:green_bed",
                "minecraft:red_bed",
                "minecraft:black_bed",
                "minecraft:filled_map",
                "minecraft:shears",
                "minecraft:potion",
                "minecraft:carrot_on_a_stick",
                "minecraft:rabbit_stew",
                "minecraft:iron_horse_armor",
                "minecraft:golden_horse_armor",
                "minecraft:diamond_horse_armor",
                "minecraft:beetroot_soup",
                "minecraft:splash_potion",
                "minecraft:lingering_potion",
                "minecraft:shield",
                "minecraft:elytra",
                "minecraft:totem_of_undying",
                "minecraft:trident",
                "minecraft:turtle_helmet",
                "minecraft:music_disc_13",
                "minecraft:music_disc_cat",
                "minecraft:music_disc_blocks",
                "minecraft:music_disc_chirp",
                "minecraft:music_disc_far",
                "minecraft:music_disc_mall",
                "minecraft:music_disc_mellohi",
                "minecraft:music_disc_stal",
                "minecraft:music_disc_strad",
                "minecraft:music_disc_ward",
                "minecraft:music_disc_11",
                "minecraft:music_disc_wait",
                "minecraft:creeper_banner_pattern",
                "minecraft:crossbow",
                "minecraft:flower_banner_pattern",
                "minecraft:globe_banner_pattern",
                "minecraft:leather_horse_armor",
                "minecraft:mojang_banner_pattern",
                "minecraft:skull_banner_pattern",
                "minecraft:suspicious_stew",
                "minecraft:netherite_axe",
                "minecraft:netherite_boots",
                "minecraft:netherite_chestplate",
                "minecraft:netherite_helmet",
                "minecraft:netherite_hoe",
                "minecraft:netherite_leggings",
                "minecraft:netherite_pickaxe",
                "minecraft:netherite_shovel",
                "minecraft:netherite_sword",
                "minecraft:warped_fungus_on_a_stick",
                "minecraft:music_disc_pigstep",
                "minecraft:piglin_banner_pattern",
                "minecraft:axolotl_bucket",
                "minecraft:music_disc_otherside"
            ]
        },
        "7b5f1570-b945-49ba-aaed-4a61a82edd79": {
            "id": "7b5f1570-b945-49ba-aaed-4a61a82edd79",
            "name": "Somente Criativo",
            "icon": "minecraft:command_block",
            "items": [
                "minecraft:bedrock",
                "minecraft:petrified_oak_slab",
                "minecraft:spawner",
                "minecraft:farmland",
                "minecraft:frosted_ice",
                "minecraft:end_portal_frame",
                "minecraft:chorus_plant",
                "minecraft:command_block_minecart",
                "minecraft:knowledge_book",
                "minecraft:elder_guardian_spawn_egg",
                "minecraft:wither_skeleton_spawn_egg",
                "minecraft:stray_spawn_egg",
                "minecraft:husk_spawn_egg",
                "minecraft:zombie_villager_spawn_egg",
                "minecraft:skeleton_horse_spawn_egg",
                "minecraft:zombie_horse_spawn_egg",
                "minecraft:donkey_spawn_egg",
                "minecraft:mule_spawn_egg",
                "minecraft:evoker_spawn_egg",
                "minecraft:vex_spawn_egg",
                "minecraft:vindicator_spawn_egg",
                "minecraft:creeper_spawn_egg",
                "minecraft:skeleton_spawn_egg",
                "minecraft:spider_spawn_egg",
                "minecraft:zombie_spawn_egg",
                "minecraft:slime_spawn_egg",
                "minecraft:ghast_spawn_egg",
                "minecraft:zombified_piglin_spawn_egg",
                "minecraft:enderman_spawn_egg",
                "minecraft:cave_spider_spawn_egg",
                "minecraft:silverfish_spawn_egg",
                "minecraft:blaze_spawn_egg",
                "minecraft:magma_cube_spawn_egg",
                "minecraft:bat_spawn_egg",
                "minecraft:witch_spawn_egg",
                "minecraft:endermite_spawn_egg",
                "minecraft:guardian_spawn_egg",
                "minecraft:shulker_spawn_egg",
                "minecraft:pig_spawn_egg",
                "minecraft:sheep_spawn_egg",
                "minecraft:cow_spawn_egg",
                "minecraft:chicken_spawn_egg",
                "minecraft:squid_spawn_egg",
                "minecraft:wolf_spawn_egg",
                "minecraft:mooshroom_spawn_egg",
                "minecraft:ocelot_spawn_egg",
                "minecraft:parrot_spawn_egg",
                "minecraft:horse_spawn_egg",
                "minecraft:rabbit_spawn_egg",
                "minecraft:polar_bear_spawn_egg",
                "minecraft:llama_spawn_egg",
                "minecraft:villager_spawn_egg",
                "minecraft:turtle_spawn_egg",
                "minecraft:cod_spawn_egg",
                "minecraft:salmon_spawn_egg",
                "minecraft:pufferfish_spawn_egg",
                "minecraft:phantom_spawn_egg",
                "minecraft:tropical_fish_spawn_egg",
                "minecraft:drowned_spawn_egg",
                "minecraft:dolphin_spawn_egg",
                "minecraft:player_head",
                "minecraft:command_block",
                "minecraft:repeating_command_block",
                "minecraft:chain_command_block",
                "minecraft:barrier",
                "minecraft:structure_block",
                "minecraft:structure_void",
                "minecraft:debug_stick",
                "minecraft:jigsaw",
                "minecraft:cat_spawn_egg",
                "minecraft:fox_spawn_egg",
                "minecraft:panda_spawn_egg",
                "minecraft:pillager_spawn_egg",
                "minecraft:ravager_spawn_egg",
                "minecraft:trader_llama_spawn_egg",
                "minecraft:wandering_trader_spawn_egg",
                "minecraft:bee_spawn_egg",
                "minecraft:hoglin_spawn_egg",
                "minecraft:piglin_spawn_egg",
                "minecraft:piglin_brute_spawn_egg",
                "minecraft:strider_spawn_egg",
                "minecraft:zoglin_spawn_egg",
                "minecraft:budding_amethyst",
                "minecraft:bundle",
                "minecraft:glow_squid_spawn_egg",
                "minecraft:goat_spawn_egg",
                "minecraft:axolotl_spawn_egg",
                "minecraft:light"
            ]
        },
        "c4945c01-8926-4737-a149-f3b83e6881a4": {
            "id": "c4945c01-8926-4737-a149-f3b83e6881a4",
            "name": "Fornalhas",
            "icon": "minecraft:furnace",
            "items": [
                "minecraft:porkchop",
                "minecraft:beef",
                "minecraft:chicken",
                "minecraft:rabbit",
                "minecraft:mutton",
                "minecraft:ancient_debris",
                "minecraft:raw_copper",
                "minecraft:raw_gold",
                "minecraft:raw_iron"
            ]
        },
        "5feeb9a0-0d40-4874-be24-d9f3ec0fed9b": {
            "id": "5feeb9a0-0d40-4874-be24-d9f3ec0fed9b",
            "name": "Bétula",
            "icon": "minecraft:birch_log",
            "items": [
                "minecraft:birch_planks",
                "minecraft:birch_sapling",
                "minecraft:birch_log",
                "minecraft:birch_wood",
                "minecraft:stripped_birch_log",
                "minecraft:stripped_birch_wood",
                "minecraft:birch_slab",
                "minecraft:birch_stairs",
                "minecraft:birch_pressure_plate",
                "minecraft:birch_fence",
                "minecraft:birch_fence_gate",
                "minecraft:birch_door",
                "minecraft:birch_trapdoor",
                "minecraft:birch_button",
                "minecraft:birch_sign"
            ]
        },
        "f732878d-732b-4e0b-9221-05e4546a5df0": {
            "id": "f732878d-732b-4e0b-9221-05e4546a5df0",
            "name": "Pinheiro",
            "icon": "minecraft:spruce_log",
            "items": [
                "minecraft:spruce_planks",
                "minecraft:spruce_sapling",
                "minecraft:spruce_log",
                "minecraft:spruce_wood",
                "minecraft:stripped_spruce_log",
                "minecraft:stripped_spruce_wood",
                "minecraft:spruce_slab",
                "minecraft:spruce_stairs",
                "minecraft:spruce_pressure_plate",
                "minecraft:spruce_fence",
                "minecraft:spruce_fence_gate",
                "minecraft:spruce_door",
                "minecraft:spruce_trapdoor",
                "minecraft:spruce_button",
                "minecraft:spruce_sign"
            ]
        },
        "f1483c72-6100-4e5d-aca2-1f6c6361413e": {
            "id": "f1483c72-6100-4e5d-aca2-1f6c6361413e",
            "name": "Selva",
            "icon": "minecraft:jungle_log",
            "items": [
                "minecraft:jungle_planks",
                "minecraft:jungle_sapling",
                "minecraft:jungle_log",
                "minecraft:jungle_wood",
                "minecraft:stripped_jungle_log",
                "minecraft:stripped_jungle_wood",
                "minecraft:jungle_slab",
                "minecraft:jungle_stairs",
                "minecraft:jungle_pressure_plate",
                "minecraft:jungle_fence",
                "minecraft:jungle_fence_gate",
                "minecraft:jungle_door",
                "minecraft:jungle_trapdoor",
                "minecraft:jungle_button",
                "minecraft:jungle_sign"
            ]
        },
        "a6f059e2-518b-452b-9759-ef159770897c": {
            "id": "a6f059e2-518b-452b-9759-ef159770897c",
            "name": "Carvalho",
            "icon": "minecraft:oak_log",
            "items": [
                "minecraft:oak_planks",
                "minecraft:oak_sapling",
                "minecraft:oak_log",
                "minecraft:oak_wood",
                "minecraft:stripped_oak_log",
                "minecraft:stripped_oak_wood",
                "minecraft:oak_slab",
                "minecraft:oak_stairs",
                "minecraft:oak_pressure_plate",
                "minecraft:oak_fence",
                "minecraft:oak_fence_gate",
                "minecraft:oak_door",
                "minecraft:oak_trapdoor",
                "minecraft:oak_button",
                "minecraft:oak_sign"
            ]
        },
        "f8b8e062-3bc7-4e0a-87df-7381747acea6": {
            "id": "f8b8e062-3bc7-4e0a-87df-7381747acea6",
            "name": "Carvalho Escuro",
            "icon": "minecraft:dark_oak_log",
            "items": [
                "minecraft:dark_oak_planks",
                "minecraft:dark_oak_sapling",
                "minecraft:dark_oak_log",
                "minecraft:dark_oak_wood",
                "minecraft:stripped_dark_oak_log",
                "minecraft:stripped_dark_oak_wood",
                "minecraft:dark_oak_slab",
                "minecraft:dark_oak_stairs",
                "minecraft:dark_oak_pressure_plate",
                "minecraft:dark_oak_fence",
                "minecraft:dark_oak_fence_gate",
                "minecraft:dark_oak_door",
                "minecraft:dark_oak_trapdoor",
                "minecraft:dark_oak_button",
                "minecraft:dark_oak_sign"
            ]
        },
        "5aae41cc-8854-49c2-9c86-0e028dd1b77e": {
            "id": "5aae41cc-8854-49c2-9c86-0e028dd1b77e",
            "name": "Acácia",
            "icon": "minecraft:acacia_log",
            "items": [
                "minecraft:acacia_planks",
                "minecraft:acacia_sapling",
                "minecraft:acacia_log",
                "minecraft:acacia_wood",
                "minecraft:stripped_acacia_log",
                "minecraft:stripped_acacia_wood",
                "minecraft:acacia_slab",
                "minecraft:acacia_stairs",
                "minecraft:acacia_pressure_plate",
                "minecraft:acacia_fence",
                "minecraft:acacia_fence_gate",
                "minecraft:acacia_door",
                "minecraft:acacia_trapdoor",
                "minecraft:acacia_button",
                "minecraft:acacia_sign"
            ]
        },
        "f495d4f1-29c5-48cf-b5ec-c8a425721cca": {
            "id": "f495d4f1-29c5-48cf-b5ec-c8a425721cca",
            "name": "Branco",
            "icon": "minecraft:white_dye",
            "items": [
                "minecraft:white_wool",
                "minecraft:white_stained_glass",
                "minecraft:white_terracotta",
                "minecraft:white_stained_glass_pane",
                "minecraft:white_carpet",
                "minecraft:white_glazed_terracotta",
                "minecraft:white_concrete",
                "minecraft:white_concrete_powder",
                "minecraft:white_banner",
                "minecraft:white_dye",
                "minecraft:white_candle"
            ]
        },
        "6a2e8ac3-4f29-4786-a78b-fce2af534f25": {
            "id": "6a2e8ac3-4f29-4786-a78b-fce2af534f25",
            "name": "Laranja",
            "icon": "minecraft:orange_dye",
            "items": [
                "minecraft:orange_wool",
                "minecraft:orange_stained_glass",
                "minecraft:orange_terracotta",
                "minecraft:orange_stained_glass_pane",
                "minecraft:orange_carpet",
                "minecraft:orange_glazed_terracotta",
                "minecraft:orange_concrete",
                "minecraft:orange_concrete_powder",
                "minecraft:orange_dye",
                "minecraft:orange_banner",
                "minecraft:orange_candle"
            ]
        },
        "a546a45e-5406-498a-b0b6-d2fafc299b48": {
            "id": "a546a45e-5406-498a-b0b6-d2fafc299b48",
            "name": "Magenta",
            "icon": "minecraft:magenta_dye",
            "items": [
                "minecraft:magenta_wool",
                "minecraft:magenta_stained_glass",
                "minecraft:magenta_terracotta",
                "minecraft:magenta_stained_glass_pane",
                "minecraft:magenta_carpet",
                "minecraft:magenta_glazed_terracotta",
                "minecraft:magenta_concrete",
                "minecraft:magenta_concrete_powder",
                "minecraft:magenta_dye",
                "minecraft:magenta_banner",
                "minecraft:magenta_candle"
            ]
        },
        "30a06635-89c3-46fe-bd94-a69cad118ffb": {
            "id": "30a06635-89c3-46fe-bd94-a69cad118ffb",
            "name": "Azul Claro",
            "icon": "minecraft:light_blue_dye",
            "items": [
                "minecraft:light_blue_wool",
                "minecraft:light_blue_stained_glass",
                "minecraft:light_blue_terracotta",
                "minecraft:light_blue_stained_glass_pane",
                "minecraft:light_blue_carpet",
                "minecraft:light_blue_glazed_terracotta",
                "minecraft:light_blue_concrete",
                "minecraft:light_blue_concrete_powder",
                "minecraft:light_blue_dye",
                "minecraft:light_blue_banner",
                "minecraft:light_blue_candle"
            ]
        },
        "9aaf491d-b6a6-40c1-9826-c476bb607666": {
            "id": "9aaf491d-b6a6-40c1-9826-c476bb607666",
            "name": "Amarelo",
            "icon": "minecraft:yellow_dye",
            "items": [
                "minecraft:yellow_wool",
                "minecraft:yellow_stained_glass",
                "minecraft:yellow_terracotta",
                "minecraft:yellow_stained_glass_pane",
                "minecraft:yellow_carpet",
                "minecraft:yellow_glazed_terracotta",
                "minecraft:yellow_concrete",
                "minecraft:yellow_concrete_powder",
                "minecraft:yellow_dye",
                "minecraft:yellow_banner",
                "minecraft:yellow_candle"
            ]
        },
        "70415771-b8d1-4011-ad2b-5749ee1c2711": {
            "id": "70415771-b8d1-4011-ad2b-5749ee1c2711",
            "name": "Verde Limao",
            "icon": "minecraft:lime_dye",
            "items": [
                "minecraft:lime_wool",
                "minecraft:lime_stained_glass",
                "minecraft:lime_terracotta",
                "minecraft:lime_stained_glass_pane",
                "minecraft:lime_carpet",
                "minecraft:lime_glazed_terracotta",
                "minecraft:lime_concrete",
                "minecraft:lime_concrete_powder",
                "minecraft:lime_dye",
                "minecraft:lime_banner",
                "minecraft:lime_candle"
            ]
        },
        "c8945d8c-d581-43d6-b3fa-63e842b84ccd": {
            "id": "c8945d8c-d581-43d6-b3fa-63e842b84ccd",
            "name": "Rosa",
            "icon": "minecraft:pink_dye",
            "items": [
                "minecraft:pink_wool",
                "minecraft:pink_stained_glass",
                "minecraft:pink_terracotta",
                "minecraft:pink_stained_glass_pane",
                "minecraft:pink_carpet",
                "minecraft:pink_glazed_terracotta",
                "minecraft:pink_concrete",
                "minecraft:pink_concrete_powder",
                "minecraft:pink_dye",
                "minecraft:pink_banner",
                "minecraft:pink_candle"
            ]
        },
        "22f356d9-2663-4b42-8272-5b420ac33f9e": {
            "id": "22f356d9-2663-4b42-8272-5b420ac33f9e",
            "name": "Cinza",
            "icon": "minecraft:gray_dye",
            "items": [
                "minecraft:gray_wool",
                "minecraft:gray_stained_glass",
                "minecraft:gray_terracotta",
                "minecraft:gray_stained_glass_pane",
                "minecraft:gray_carpet",
                "minecraft:gray_glazed_terracotta",
                "minecraft:gray_concrete",
                "minecraft:gray_concrete_powder",
                "minecraft:gray_dye",
                "minecraft:gray_banner",
                "minecraft:gray_candle"
            ]
        },
        "f95e86b5-6f38-423b-ba0c-b9baedd4bad4": {
            "id": "f95e86b5-6f38-423b-ba0c-b9baedd4bad4",
            "name": "Cinza Claro",
            "icon": "minecraft:light_gray_dye",
            "items": [
                "minecraft:light_gray_wool",
                "minecraft:light_gray_stained_glass",
                "minecraft:light_gray_terracotta",
                "minecraft:light_gray_stained_glass_pane",
                "minecraft:light_gray_carpet",
                "minecraft:light_gray_glazed_terracotta",
                "minecraft:light_gray_concrete",
                "minecraft:light_gray_concrete_powder",
                "minecraft:light_gray_dye",
                "minecraft:light_gray_banner",
                "minecraft:light_gray_candle"
            ]
        },
        "d16460a0-e0ab-46b7-899a-aa5667ffc7a1": {
            "id": "d16460a0-e0ab-46b7-899a-aa5667ffc7a1",
            "name": "Ciano",
            "icon": "minecraft:cyan_dye",
            "items": [
                "minecraft:cyan_wool",
                "minecraft:cyan_stained_glass",
                "minecraft:cyan_terracotta",
                "minecraft:cyan_stained_glass_pane",
                "minecraft:cyan_carpet",
                "minecraft:cyan_glazed_terracotta",
                "minecraft:cyan_concrete",
                "minecraft:cyan_concrete_powder",
                "minecraft:cyan_dye",
                "minecraft:cyan_banner",
                "minecraft:cyan_candle"
            ]
        },
        "76684468-0636-4849-87e3-95249325676b": {
            "id": "76684468-0636-4849-87e3-95249325676b",
            "name": "Roxo",
            "icon": "minecraft:purple_dye",
            "items": [
                "minecraft:purple_wool",
                "minecraft:purple_stained_glass",
                "minecraft:purple_terracotta",
                "minecraft:purple_stained_glass_pane",
                "minecraft:purple_carpet",
                "minecraft:purple_glazed_terracotta",
                "minecraft:purple_concrete",
                "minecraft:purple_concrete_powder",
                "minecraft:purple_dye",
                "minecraft:purple_banner",
                "minecraft:purple_candle"
            ]
        },
        "f397a635-9c1d-4f19-81e4-e205f82c3d69": {
            "id": "f397a635-9c1d-4f19-81e4-e205f82c3d69",
            "name": "Azul",
            "icon": "minecraft:blue_dye",
            "items": [
                "minecraft:blue_wool",
                "minecraft:blue_stained_glass",
                "minecraft:blue_terracotta",
                "minecraft:blue_stained_glass_pane",
                "minecraft:blue_carpet",
                "minecraft:blue_glazed_terracotta",
                "minecraft:blue_concrete",
                "minecraft:blue_concrete_powder",
                "minecraft:blue_banner",
                "minecraft:blue_dye",
                "minecraft:blue_candle"
            ]
        },
        "2d2b8913-405e-41a5-b24c-995095e6e32c": {
            "id": "2d2b8913-405e-41a5-b24c-995095e6e32c",
            "name": "Marrom",
            "icon": "minecraft:brown_dye",
            "items": [
                "minecraft:brown_wool",
                "minecraft:brown_stained_glass",
                "minecraft:brown_terracotta",
                "minecraft:brown_stained_glass_pane",
                "minecraft:brown_carpet",
                "minecraft:brown_glazed_terracotta",
                "minecraft:brown_concrete",
                "minecraft:brown_concrete_powder",
                "minecraft:brown_banner",
                "minecraft:brown_dye",
                "minecraft:brown_candle"
            ]
        },
        "e87e8418-20e3-4a73-8335-fead03da5404": {
            "id": "e87e8418-20e3-4a73-8335-fead03da5404",
            "name": "Verde",
            "icon": "minecraft:green_dye",
            "items": [
                "minecraft:green_wool",
                "minecraft:green_stained_glass",
                "minecraft:green_terracotta",
                "minecraft:green_stained_glass_pane",
                "minecraft:green_carpet",
                "minecraft:green_glazed_terracotta",
                "minecraft:green_concrete",
                "minecraft:green_concrete_powder",
                "minecraft:green_dye",
                "minecraft:green_banner",
                "minecraft:green_candle"
            ]
        },
        "62b00652-c44d-4b4a-9d64-ba8ec84780e1": {
            "id": "62b00652-c44d-4b4a-9d64-ba8ec84780e1",
            "name": "Vermelho",
            "icon": "minecraft:red_dye",
            "items": [
                "minecraft:red_wool",
                "minecraft:red_stained_glass",
                "minecraft:red_terracotta",
                "minecraft:red_stained_glass_pane",
                "minecraft:red_carpet",
                "minecraft:red_glazed_terracotta",
                "minecraft:red_concrete",
                "minecraft:red_concrete_powder",
                "minecraft:red_dye",
                "minecraft:red_banner",
                "minecraft:red_candle"
            ]
        },
        "58ab7a27-7dd7-4b59-b83a-d99bb53c0bfb": {
            "id": "58ab7a27-7dd7-4b59-b83a-d99bb53c0bfb",
            "name": "Preto",
            "icon": "minecraft:black_dye",
            "items": [
                "minecraft:black_wool",
                "minecraft:black_stained_glass",
                "minecraft:black_terracotta",
                "minecraft:black_stained_glass_pane",
                "minecraft:black_carpet",
                "minecraft:black_glazed_terracotta",
                "minecraft:black_concrete",
                "minecraft:black_concrete_powder",
                "minecraft:black_banner",
                "minecraft:black_dye",
                "minecraft:black_candle"
            ]
        },
        "0ddccd36-039c-47c8-9c61-bb2ff992374d": {
            "id": "0ddccd36-039c-47c8-9c61-bb2ff992374d",
            "name": "Terreno",
            "icon": "minecraft:grass_block",
            "items": [
                "minecraft:grass_block",
                "minecraft:coarse_dirt",
                "minecraft:podzol",
                "minecraft:mycelium",
                "minecraft:dirt_path"
            ]
        },
        "4e66e683-83f6-4f38-a40f-98db5672e02b": {
            "id": "4e66e683-83f6-4f38-a40f-98db5672e02b",
            "name": "Subterraneo",
            "icon": "minecraft:stone",
            "items": [
                "minecraft:granite",
                "minecraft:polished_granite",
                "minecraft:diorite",
                "minecraft:polished_diorite",
                "minecraft:andesite",
                "minecraft:polished_andesite"
            ]
        }
    },
    "categories_order": [
        "536ba551-b256-4a68-bbb8-26e42d4f3115",
        "0ddccd36-039c-47c8-9c61-bb2ff992374d",
        "4e66e683-83f6-4f38-a40f-98db5672e02b",
        "f495d4f1-29c5-48cf-b5ec-c8a425721cca",
        "f95e86b5-6f38-423b-ba0c-b9baedd4bad4",
        "22f356d9-2663-4b42-8272-5b420ac33f9e",
        "58ab7a27-7dd7-4b59-b83a-d99bb53c0bfb",
        "62b00652-c44d-4b4a-9d64-ba8ec84780e1",
        "6a2e8ac3-4f29-4786-a78b-fce2af534f25",
        "9aaf491d-b6a6-40c1-9826-c476bb607666",
        "c8945d8c-d581-43d6-b3fa-63e842b84ccd",
        "a546a45e-5406-498a-b0b6-d2fafc299b48",
        "76684468-0636-4849-87e3-95249325676b",
        "d16460a0-e0ab-46b7-899a-aa5667ffc7a1",
        "f397a635-9c1d-4f19-81e4-e205f82c3d69",
        "30a06635-89c3-46fe-bd94-a69cad118ffb",
        "70415771-b8d1-4011-ad2b-5749ee1c2711",
        "e87e8418-20e3-4a73-8335-fead03da5404",
        "2d2b8913-405e-41a5-b24c-995095e6e32c",
        "a6f059e2-518b-452b-9759-ef159770897c",
        "f732878d-732b-4e0b-9221-05e4546a5df0",
        "5feeb9a0-0d40-4874-be24-d9f3ec0fed9b",
        "f1483c72-6100-4e5d-aca2-1f6c6361413e",
        "5aae41cc-8854-49c2-9c86-0e028dd1b77e",
        "f8b8e062-3bc7-4e0a-87df-7381747acea6",
        "c4945c01-8926-4737-a149-f3b83e6881a4",
        "26b8ca6b-c979-476a-a6e1-76954ef3d95f",
        "7b5f1570-b945-49ba-aaed-4a61a82edd79"
    ]
}

export default Preset;