import { PresetType } from ".";

const Preset: PresetType =
{
    name: "Nivel Zero",
    icon: "minecraft:redstone",
    uncategorized: null,
    categories: {
        "536ba551-b256-4a68-bbb8-26e42d4f3115": {
            "id": "536ba551-b256-4a68-bbb8-26e42d4f3115",
            "name": "Silos",
            "icon": "minecraft:barrel",
            "items": [
                "minecraft:stone",
                "minecraft:deepslate",
                "minecraft:cobbled_deepslate",
                "minecraft:dirt",
                "minecraft:cobblestone",
                "minecraft:sand",
                "minecraft:gravel",
                "minecraft:netherrack"
            ]
        },
        "26b8ca6b-c979-476a-a6e1-76954ef3d95f": {
            "id": "26b8ca6b-c979-476a-a6e1-76954ef3d95f",
            "name": "Não Junta",
            "icon": "minecraft:barrier",
            "items": [
                "minecraft:shulker_box",
                "minecraft:white_shulker_box",
                "minecraft:orange_shulker_box",
                "minecraft:magenta_shulker_box",
                "minecraft:light_blue_shulker_box",
                "minecraft:yellow_shulker_box",
                "minecraft:lime_shulker_box",
                "minecraft:pink_shulker_box",
                "minecraft:gray_shulker_box",
                "minecraft:light_gray_shulker_box",
                "minecraft:cyan_shulker_box",
                "minecraft:purple_shulker_box",
                "minecraft:blue_shulker_box",
                "minecraft:brown_shulker_box",
                "minecraft:green_shulker_box",
                "minecraft:red_shulker_box",
                "minecraft:black_shulker_box",
                "minecraft:saddle",
                "minecraft:minecart",
                "minecraft:chest_minecart",
                "minecraft:furnace_minecart",
                "minecraft:tnt_minecart",
                "minecraft:hopper_minecart",
                "minecraft:carrot_on_a_stick",
                "minecraft:warped_fungus_on_a_stick",
                "minecraft:elytra",
                "minecraft:oak_boat",
                "minecraft:oak_chest_boat",
                "minecraft:spruce_boat",
                "minecraft:spruce_chest_boat",
                "minecraft:birch_boat",
                "minecraft:birch_chest_boat",
                "minecraft:jungle_boat",
                "minecraft:jungle_chest_boat",
                "minecraft:acacia_boat",
                "minecraft:acacia_chest_boat",
                "minecraft:dark_oak_boat",
                "minecraft:dark_oak_chest_boat",
                "minecraft:mangrove_boat",
                "minecraft:mangrove_chest_boat",
                "minecraft:turtle_helmet",
                "minecraft:flint_and_steel",
                "minecraft:bow",
                "minecraft:wooden_sword",
                "minecraft:wooden_shovel",
                "minecraft:wooden_pickaxe",
                "minecraft:wooden_axe",
                "minecraft:wooden_hoe",
                "minecraft:stone_sword",
                "minecraft:stone_shovel",
                "minecraft:stone_pickaxe",
                "minecraft:stone_axe",
                "minecraft:stone_hoe",
                "minecraft:golden_sword",
                "minecraft:golden_shovel",
                "minecraft:golden_pickaxe",
                "minecraft:golden_axe",
                "minecraft:golden_hoe",
                "minecraft:iron_sword",
                "minecraft:iron_shovel",
                "minecraft:iron_pickaxe",
                "minecraft:iron_axe",
                "minecraft:iron_hoe",
                "minecraft:diamond_sword",
                "minecraft:diamond_shovel",
                "minecraft:diamond_pickaxe",
                "minecraft:diamond_axe",
                "minecraft:diamond_hoe",
                "minecraft:netherite_sword",
                "minecraft:netherite_shovel",
                "minecraft:netherite_pickaxe",
                "minecraft:netherite_axe",
                "minecraft:netherite_hoe",
                "minecraft:mushroom_stew",
                "minecraft:leather_helmet",
                "minecraft:leather_chestplate",
                "minecraft:leather_leggings",
                "minecraft:leather_boots",
                "minecraft:chainmail_helmet",
                "minecraft:chainmail_chestplate",
                "minecraft:chainmail_leggings",
                "minecraft:chainmail_boots",
                "minecraft:iron_helmet",
                "minecraft:iron_chestplate",
                "minecraft:iron_leggings",
                "minecraft:iron_boots",
                "minecraft:diamond_helmet",
                "minecraft:diamond_chestplate",
                "minecraft:diamond_leggings",
                "minecraft:diamond_boots",
                "minecraft:golden_helmet",
                "minecraft:golden_chestplate",
                "minecraft:golden_leggings",
                "minecraft:golden_boots",
                "minecraft:netherite_helmet",
                "minecraft:netherite_chestplate",
                "minecraft:netherite_leggings",
                "minecraft:netherite_boots",
                "minecraft:water_bucket",
                "minecraft:lava_bucket",
                "minecraft:powder_snow_bucket",
                "minecraft:milk_bucket",
                "minecraft:pufferfish_bucket",
                "minecraft:salmon_bucket",
                "minecraft:cod_bucket",
                "minecraft:tropical_fish_bucket",
                "minecraft:axolotl_bucket",
                "minecraft:tadpole_bucket",
                "minecraft:fishing_rod",
                "minecraft:spyglass",
                "minecraft:cake",
                "minecraft:white_bed",
                "minecraft:orange_bed",
                "minecraft:magenta_bed",
                "minecraft:light_blue_bed",
                "minecraft:yellow_bed",
                "minecraft:lime_bed",
                "minecraft:pink_bed",
                "minecraft:gray_bed",
                "minecraft:light_gray_bed",
                "minecraft:cyan_bed",
                "minecraft:purple_bed",
                "minecraft:blue_bed",
                "minecraft:brown_bed",
                "minecraft:green_bed",
                "minecraft:red_bed",
                "minecraft:black_bed",
                "minecraft:filled_map",
                "minecraft:shears",
                "minecraft:potion",
                "minecraft:writable_book",
                "minecraft:enchanted_book",
                "minecraft:rabbit_stew",
                "minecraft:iron_horse_armor",
                "minecraft:golden_horse_armor",
                "minecraft:diamond_horse_armor",
                "minecraft:leather_horse_armor",
                "minecraft:beetroot_soup",
                "minecraft:splash_potion",
                "minecraft:lingering_potion",
                "minecraft:shield",
                "minecraft:totem_of_undying",
                "minecraft:music_disc_13",
                "minecraft:music_disc_cat",
                "minecraft:music_disc_blocks",
                "minecraft:music_disc_chirp",
                "minecraft:music_disc_far",
                "minecraft:music_disc_mall",
                "minecraft:music_disc_mellohi",
                "minecraft:music_disc_stal",
                "minecraft:music_disc_strad",
                "minecraft:music_disc_ward",
                "minecraft:music_disc_11",
                "minecraft:music_disc_wait",
                "minecraft:music_disc_otherside",
                "minecraft:music_disc_5",
                "minecraft:music_disc_pigstep",
                "minecraft:trident",
                "minecraft:crossbow",
                "minecraft:suspicious_stew",
                "minecraft:flower_banner_pattern",
                "minecraft:creeper_banner_pattern",
                "minecraft:skull_banner_pattern",
                "minecraft:mojang_banner_pattern",
                "minecraft:globe_banner_pattern",
                "minecraft:piglin_banner_pattern",
                "minecraft:goat_horn"
            ]
        },
        "7b5f1570-b945-49ba-aaed-4a61a82edd79": {
            "id": "7b5f1570-b945-49ba-aaed-4a61a82edd79",
            "name": "Somente Criativo",
            "icon": "minecraft:command_block",
            "items": [
                "minecraft:bedrock",
                "minecraft:budding_amethyst",
                "minecraft:frosted_ice",
                "minecraft:petrified_oak_slab",
                "minecraft:chorus_plant",
                "minecraft:spawner",
                "minecraft:farmland",
                "minecraft:infested_stone",
                "minecraft:infested_cobblestone",
                "minecraft:infested_stone_bricks",
                "minecraft:infested_mossy_stone_bricks",
                "minecraft:infested_cracked_stone_bricks",
                "minecraft:infested_chiseled_stone_bricks",
                "minecraft:reinforced_deepslate",
                "minecraft:end_portal_frame",
                "minecraft:command_block",
                "minecraft:barrier",
                "minecraft:light",
                "minecraft:repeating_command_block",
                "minecraft:chain_command_block",
                "minecraft:structure_void",
                "minecraft:structure_block",
                "minecraft:jigsaw",
                "minecraft:bundle",
                "minecraft:allay_spawn_egg",
                "minecraft:axolotl_spawn_egg",
                "minecraft:bat_spawn_egg",
                "minecraft:bee_spawn_egg",
                "minecraft:blaze_spawn_egg",
                "minecraft:cat_spawn_egg",
                "minecraft:cave_spider_spawn_egg",
                "minecraft:chicken_spawn_egg",
                "minecraft:cod_spawn_egg",
                "minecraft:cow_spawn_egg",
                "minecraft:creeper_spawn_egg",
                "minecraft:dolphin_spawn_egg",
                "minecraft:donkey_spawn_egg",
                "minecraft:drowned_spawn_egg",
                "minecraft:elder_guardian_spawn_egg",
                "minecraft:enderman_spawn_egg",
                "minecraft:endermite_spawn_egg",
                "minecraft:evoker_spawn_egg",
                "minecraft:fox_spawn_egg",
                "minecraft:frog_spawn_egg",
                "minecraft:ghast_spawn_egg",
                "minecraft:glow_squid_spawn_egg",
                "minecraft:goat_spawn_egg",
                "minecraft:guardian_spawn_egg",
                "minecraft:hoglin_spawn_egg",
                "minecraft:horse_spawn_egg",
                "minecraft:husk_spawn_egg",
                "minecraft:llama_spawn_egg",
                "minecraft:magma_cube_spawn_egg",
                "minecraft:mooshroom_spawn_egg",
                "minecraft:mule_spawn_egg",
                "minecraft:ocelot_spawn_egg",
                "minecraft:panda_spawn_egg",
                "minecraft:parrot_spawn_egg",
                "minecraft:phantom_spawn_egg",
                "minecraft:pig_spawn_egg",
                "minecraft:piglin_spawn_egg",
                "minecraft:piglin_brute_spawn_egg",
                "minecraft:pillager_spawn_egg",
                "minecraft:polar_bear_spawn_egg",
                "minecraft:pufferfish_spawn_egg",
                "minecraft:rabbit_spawn_egg",
                "minecraft:ravager_spawn_egg",
                "minecraft:salmon_spawn_egg",
                "minecraft:sheep_spawn_egg",
                "minecraft:shulker_spawn_egg",
                "minecraft:silverfish_spawn_egg",
                "minecraft:skeleton_spawn_egg",
                "minecraft:skeleton_horse_spawn_egg",
                "minecraft:slime_spawn_egg",
                "minecraft:spider_spawn_egg",
                "minecraft:squid_spawn_egg",
                "minecraft:stray_spawn_egg",
                "minecraft:strider_spawn_egg",
                "minecraft:tadpole_spawn_egg",
                "minecraft:trader_llama_spawn_egg",
                "minecraft:tropical_fish_spawn_egg",
                "minecraft:turtle_spawn_egg",
                "minecraft:vex_spawn_egg",
                "minecraft:villager_spawn_egg",
                "minecraft:vindicator_spawn_egg",
                "minecraft:wandering_trader_spawn_egg",
                "minecraft:warden_spawn_egg",
                "minecraft:witch_spawn_egg",
                "minecraft:wither_skeleton_spawn_egg",
                "minecraft:wolf_spawn_egg",
                "minecraft:zoglin_spawn_egg",
                "minecraft:zombie_spawn_egg",
                "minecraft:zombie_horse_spawn_egg",
                "minecraft:zombie_villager_spawn_egg",
                "minecraft:zombified_piglin_spawn_egg",
                "minecraft:player_head",
                "minecraft:command_block_minecart",
                "minecraft:knowledge_book",
                "minecraft:debug_stick",
                "minecraft:frogspawn"
            ]
        },
        "c4945c01-8926-4737-a149-f3b83e6881a4": {
            "id": "c4945c01-8926-4737-a149-f3b83e6881a4",
            "name": "Fornalhas",
            "icon": "minecraft:furnace",
            "items": [
                "minecraft:ancient_debris",
                "minecraft:raw_iron",
                "minecraft:raw_copper",
                "minecraft:raw_gold",
                "minecraft:porkchop",
                "minecraft:cod",
                "minecraft:salmon",
                "minecraft:tropical_fish",
                "minecraft:beef",
                "minecraft:chicken",
                "minecraft:rabbit",
                "minecraft:mutton",
                "minecraft:chorus_fruit"
            ]
        },
        "5feeb9a0-0d40-4874-be24-d9f3ec0fed9b": {
            "id": "5feeb9a0-0d40-4874-be24-d9f3ec0fed9b",
            "name": "Bétula",
            "icon": "minecraft:birch_log",
            "items": [
                "minecraft:birch_planks",
                "minecraft:birch_sapling",
                "minecraft:birch_log",
                "minecraft:birch_wood",
                "minecraft:stripped_birch_log",
                "minecraft:stripped_birch_wood",
                "minecraft:birch_slab",
                "minecraft:birch_stairs",
                "minecraft:birch_pressure_plate",
                "minecraft:birch_fence",
                "minecraft:birch_fence_gate",
                "minecraft:birch_door",
                "minecraft:birch_trapdoor",
                "minecraft:birch_button",
                "minecraft:birch_sign"
            ]
        },
        "f732878d-732b-4e0b-9221-05e4546a5df0": {
            "id": "f732878d-732b-4e0b-9221-05e4546a5df0",
            "name": "Pinheiro",
            "icon": "minecraft:spruce_log",
            "items": [
                "minecraft:spruce_planks",
                "minecraft:spruce_sapling",
                "minecraft:spruce_log",
                "minecraft:spruce_wood",
                "minecraft:stripped_spruce_log",
                "minecraft:stripped_spruce_wood",
                "minecraft:spruce_slab",
                "minecraft:spruce_stairs",
                "minecraft:spruce_pressure_plate",
                "minecraft:spruce_fence",
                "minecraft:spruce_fence_gate",
                "minecraft:spruce_door",
                "minecraft:spruce_trapdoor",
                "minecraft:spruce_button",
                "minecraft:spruce_sign"
            ]
        },
        "f1483c72-6100-4e5d-aca2-1f6c6361413e": {
            "id": "f1483c72-6100-4e5d-aca2-1f6c6361413e",
            "name": "Selva",
            "icon": "minecraft:jungle_log",
            "items": [
                "minecraft:jungle_planks",
                "minecraft:jungle_sapling",
                "minecraft:jungle_log",
                "minecraft:jungle_wood",
                "minecraft:stripped_jungle_log",
                "minecraft:stripped_jungle_wood",
                "minecraft:jungle_slab",
                "minecraft:jungle_stairs",
                "minecraft:jungle_pressure_plate",
                "minecraft:jungle_fence",
                "minecraft:jungle_fence_gate",
                "minecraft:jungle_door",
                "minecraft:jungle_trapdoor",
                "minecraft:jungle_button",
                "minecraft:jungle_sign"
            ]
        },
        "a6f059e2-518b-452b-9759-ef159770897c": {
            "id": "a6f059e2-518b-452b-9759-ef159770897c",
            "name": "Carvalho",
            "icon": "minecraft:oak_log",
            "items": [
                "minecraft:oak_planks",
                "minecraft:oak_sapling",
                "minecraft:oak_log",
                "minecraft:oak_wood",
                "minecraft:stripped_oak_log",
                "minecraft:stripped_oak_wood",
                "minecraft:oak_slab",
                "minecraft:oak_stairs",
                "minecraft:oak_pressure_plate",
                "minecraft:oak_fence",
                "minecraft:oak_fence_gate",
                "minecraft:oak_door",
                "minecraft:oak_trapdoor",
                "minecraft:oak_button",
                "minecraft:oak_sign"
            ]
        },
        "f8b8e062-3bc7-4e0a-87df-7381747acea6": {
            "id": "f8b8e062-3bc7-4e0a-87df-7381747acea6",
            "name": "Carvalho Escuro",
            "icon": "minecraft:dark_oak_log",
            "items": [
                "minecraft:dark_oak_planks",
                "minecraft:dark_oak_sapling",
                "minecraft:dark_oak_log",
                "minecraft:dark_oak_wood",
                "minecraft:stripped_dark_oak_log",
                "minecraft:stripped_dark_oak_wood",
                "minecraft:dark_oak_slab",
                "minecraft:dark_oak_stairs",
                "minecraft:dark_oak_pressure_plate",
                "minecraft:dark_oak_fence",
                "minecraft:dark_oak_fence_gate",
                "minecraft:dark_oak_door",
                "minecraft:dark_oak_trapdoor",
                "minecraft:dark_oak_button",
                "minecraft:dark_oak_sign"
            ]
        },
        "5aae41cc-8854-49c2-9c86-0e028dd1b77e": {
            "id": "5aae41cc-8854-49c2-9c86-0e028dd1b77e",
            "name": "Acácia",
            "icon": "minecraft:acacia_log",
            "items": [
                "minecraft:acacia_planks",
                "minecraft:acacia_sapling",
                "minecraft:acacia_log",
                "minecraft:acacia_wood",
                "minecraft:stripped_acacia_log",
                "minecraft:stripped_acacia_wood",
                "minecraft:acacia_slab",
                "minecraft:acacia_stairs",
                "minecraft:acacia_pressure_plate",
                "minecraft:acacia_fence",
                "minecraft:acacia_fence_gate",
                "minecraft:acacia_door",
                "minecraft:acacia_trapdoor",
                "minecraft:acacia_button",
                "minecraft:acacia_sign"
            ]
        },
        "f495d4f1-29c5-48cf-b5ec-c8a425721cca": {
            "id": "f495d4f1-29c5-48cf-b5ec-c8a425721cca",
            "name": "Branco",
            "icon": "minecraft:white_wool",
            "items": [
                "minecraft:white_wool",
                "minecraft:white_stained_glass",
                "minecraft:white_terracotta",
                "minecraft:white_stained_glass_pane",
                "minecraft:white_carpet",
                "minecraft:white_glazed_terracotta",
                "minecraft:white_concrete",
                "minecraft:white_concrete_powder",
                "minecraft:white_banner",
                "minecraft:white_dye",
                "minecraft:white_candle"
            ]
        },
        "6a2e8ac3-4f29-4786-a78b-fce2af534f25": {
            "id": "6a2e8ac3-4f29-4786-a78b-fce2af534f25",
            "name": "Laranja",
            "icon": "minecraft:orange_wool",
            "items": [
                "minecraft:orange_wool",
                "minecraft:orange_stained_glass",
                "minecraft:orange_terracotta",
                "minecraft:orange_stained_glass_pane",
                "minecraft:orange_carpet",
                "minecraft:orange_glazed_terracotta",
                "minecraft:orange_concrete",
                "minecraft:orange_concrete_powder",
                "minecraft:orange_dye",
                "minecraft:orange_banner",
                "minecraft:orange_candle"
            ]
        },
        "a546a45e-5406-498a-b0b6-d2fafc299b48": {
            "id": "a546a45e-5406-498a-b0b6-d2fafc299b48",
            "name": "Magenta",
            "icon": "minecraft:magenta_wool",
            "items": [
                "minecraft:magenta_wool",
                "minecraft:magenta_stained_glass",
                "minecraft:magenta_terracotta",
                "minecraft:magenta_stained_glass_pane",
                "minecraft:magenta_carpet",
                "minecraft:magenta_glazed_terracotta",
                "minecraft:magenta_concrete",
                "minecraft:magenta_concrete_powder",
                "minecraft:magenta_dye",
                "minecraft:magenta_banner",
                "minecraft:magenta_candle"
            ]
        },
        "30a06635-89c3-46fe-bd94-a69cad118ffb": {
            "id": "30a06635-89c3-46fe-bd94-a69cad118ffb",
            "name": "Azul Claro",
            "icon": "minecraft:light_blue_wool",
            "items": [
                "minecraft:light_blue_wool",
                "minecraft:light_blue_stained_glass",
                "minecraft:light_blue_terracotta",
                "minecraft:light_blue_stained_glass_pane",
                "minecraft:light_blue_carpet",
                "minecraft:light_blue_glazed_terracotta",
                "minecraft:light_blue_concrete",
                "minecraft:light_blue_concrete_powder",
                "minecraft:light_blue_dye",
                "minecraft:light_blue_banner",
                "minecraft:light_blue_candle"
            ]
        },
        "9aaf491d-b6a6-40c1-9826-c476bb607666": {
            "id": "9aaf491d-b6a6-40c1-9826-c476bb607666",
            "name": "Amarelo",
            "icon": "minecraft:yellow_wool",
            "items": [
                "minecraft:yellow_wool",
                "minecraft:yellow_stained_glass",
                "minecraft:yellow_terracotta",
                "minecraft:yellow_stained_glass_pane",
                "minecraft:yellow_carpet",
                "minecraft:yellow_glazed_terracotta",
                "minecraft:yellow_concrete",
                "minecraft:yellow_concrete_powder",
                "minecraft:yellow_dye",
                "minecraft:yellow_banner",
                "minecraft:yellow_candle"
            ]
        },
        "70415771-b8d1-4011-ad2b-5749ee1c2711": {
            "id": "70415771-b8d1-4011-ad2b-5749ee1c2711",
            "name": "Verde Limão",
            "icon": "minecraft:lime_wool",
            "items": [
                "minecraft:lime_wool",
                "minecraft:lime_stained_glass",
                "minecraft:lime_terracotta",
                "minecraft:lime_stained_glass_pane",
                "minecraft:lime_carpet",
                "minecraft:lime_glazed_terracotta",
                "minecraft:lime_concrete",
                "minecraft:lime_concrete_powder",
                "minecraft:lime_dye",
                "minecraft:lime_banner",
                "minecraft:lime_candle"
            ]
        },
        "c8945d8c-d581-43d6-b3fa-63e842b84ccd": {
            "id": "c8945d8c-d581-43d6-b3fa-63e842b84ccd",
            "name": "Rosa",
            "icon": "minecraft:pink_wool",
            "items": [
                "minecraft:pink_wool",
                "minecraft:pink_stained_glass",
                "minecraft:pink_terracotta",
                "minecraft:pink_stained_glass_pane",
                "minecraft:pink_carpet",
                "minecraft:pink_glazed_terracotta",
                "minecraft:pink_concrete",
                "minecraft:pink_concrete_powder",
                "minecraft:pink_dye",
                "minecraft:pink_banner",
                "minecraft:pink_candle"
            ]
        },
        "22f356d9-2663-4b42-8272-5b420ac33f9e": {
            "id": "22f356d9-2663-4b42-8272-5b420ac33f9e",
            "name": "Cinza",
            "icon": "minecraft:gray_wool",
            "items": [
                "minecraft:gray_wool",
                "minecraft:gray_stained_glass",
                "minecraft:gray_terracotta",
                "minecraft:gray_stained_glass_pane",
                "minecraft:gray_carpet",
                "minecraft:gray_glazed_terracotta",
                "minecraft:gray_concrete",
                "minecraft:gray_concrete_powder",
                "minecraft:gray_dye",
                "minecraft:gray_banner",
                "minecraft:gray_candle"
            ]
        },
        "f95e86b5-6f38-423b-ba0c-b9baedd4bad4": {
            "id": "f95e86b5-6f38-423b-ba0c-b9baedd4bad4",
            "name": "Cinza Claro",
            "icon": "minecraft:light_gray_wool",
            "items": [
                "minecraft:light_gray_wool",
                "minecraft:light_gray_stained_glass",
                "minecraft:light_gray_terracotta",
                "minecraft:light_gray_stained_glass_pane",
                "minecraft:light_gray_carpet",
                "minecraft:light_gray_glazed_terracotta",
                "minecraft:light_gray_concrete",
                "minecraft:light_gray_concrete_powder",
                "minecraft:light_gray_dye",
                "minecraft:light_gray_banner",
                "minecraft:light_gray_candle"
            ]
        },
        "d16460a0-e0ab-46b7-899a-aa5667ffc7a1": {
            "id": "d16460a0-e0ab-46b7-899a-aa5667ffc7a1",
            "name": "Ciano",
            "icon": "minecraft:cyan_wool",
            "items": [
                "minecraft:cyan_wool",
                "minecraft:cyan_stained_glass",
                "minecraft:cyan_terracotta",
                "minecraft:cyan_stained_glass_pane",
                "minecraft:cyan_carpet",
                "minecraft:cyan_glazed_terracotta",
                "minecraft:cyan_concrete",
                "minecraft:cyan_concrete_powder",
                "minecraft:cyan_dye",
                "minecraft:cyan_banner",
                "minecraft:cyan_candle"
            ]
        },
        "76684468-0636-4849-87e3-95249325676b": {
            "id": "76684468-0636-4849-87e3-95249325676b",
            "name": "Roxo",
            "icon": "minecraft:purple_wool",
            "items": [
                "minecraft:purple_wool",
                "minecraft:purple_stained_glass",
                "minecraft:purple_terracotta",
                "minecraft:purple_stained_glass_pane",
                "minecraft:purple_carpet",
                "minecraft:purple_glazed_terracotta",
                "minecraft:purple_concrete",
                "minecraft:purple_concrete_powder",
                "minecraft:purple_dye",
                "minecraft:purple_banner",
                "minecraft:purple_candle"
            ]
        },
        "f397a635-9c1d-4f19-81e4-e205f82c3d69": {
            "id": "f397a635-9c1d-4f19-81e4-e205f82c3d69",
            "name": "Azul",
            "icon": "minecraft:blue_wool",
            "items": [
                "minecraft:blue_wool",
                "minecraft:blue_stained_glass",
                "minecraft:blue_terracotta",
                "minecraft:blue_stained_glass_pane",
                "minecraft:blue_carpet",
                "minecraft:blue_glazed_terracotta",
                "minecraft:blue_concrete",
                "minecraft:blue_concrete_powder",
                "minecraft:blue_banner",
                "minecraft:blue_dye",
                "minecraft:blue_candle"
            ]
        },
        "2d2b8913-405e-41a5-b24c-995095e6e32c": {
            "id": "2d2b8913-405e-41a5-b24c-995095e6e32c",
            "name": "Marrom",
            "icon": "minecraft:brown_wool",
            "items": [
                "minecraft:brown_wool",
                "minecraft:brown_stained_glass",
                "minecraft:brown_terracotta",
                "minecraft:brown_stained_glass_pane",
                "minecraft:brown_carpet",
                "minecraft:brown_glazed_terracotta",
                "minecraft:brown_concrete",
                "minecraft:brown_concrete_powder",
                "minecraft:brown_banner",
                "minecraft:brown_dye",
                "minecraft:brown_candle"
            ]
        },
        "e87e8418-20e3-4a73-8335-fead03da5404": {
            "id": "e87e8418-20e3-4a73-8335-fead03da5404",
            "name": "Verde",
            "icon": "minecraft:green_wool",
            "items": [
                "minecraft:green_wool",
                "minecraft:green_stained_glass",
                "minecraft:green_terracotta",
                "minecraft:green_stained_glass_pane",
                "minecraft:green_carpet",
                "minecraft:green_glazed_terracotta",
                "minecraft:green_concrete",
                "minecraft:green_concrete_powder",
                "minecraft:green_dye",
                "minecraft:green_banner",
                "minecraft:green_candle"
            ]
        },
        "62b00652-c44d-4b4a-9d64-ba8ec84780e1": {
            "id": "62b00652-c44d-4b4a-9d64-ba8ec84780e1",
            "name": "Vermelho",
            "icon": "minecraft:red_wool",
            "items": [
                "minecraft:red_wool",
                "minecraft:red_stained_glass",
                "minecraft:red_terracotta",
                "minecraft:red_stained_glass_pane",
                "minecraft:red_carpet",
                "minecraft:red_glazed_terracotta",
                "minecraft:red_concrete",
                "minecraft:red_concrete_powder",
                "minecraft:red_dye",
                "minecraft:red_banner",
                "minecraft:red_candle"
            ]
        },
        "58ab7a27-7dd7-4b59-b83a-d99bb53c0bfb": {
            "id": "58ab7a27-7dd7-4b59-b83a-d99bb53c0bfb",
            "name": "Preto",
            "icon": "minecraft:black_wool",
            "items": [
                "minecraft:black_wool",
                "minecraft:black_stained_glass",
                "minecraft:black_terracotta",
                "minecraft:black_stained_glass_pane",
                "minecraft:black_carpet",
                "minecraft:black_glazed_terracotta",
                "minecraft:black_concrete",
                "minecraft:black_concrete_powder",
                "minecraft:black_banner",
                "minecraft:black_dye",
                "minecraft:black_candle"
            ]
        },
        "0ddccd36-039c-47c8-9c61-bb2ff992374d": {
            "id": "0ddccd36-039c-47c8-9c61-bb2ff992374d",
            "name": "Terreno",
            "icon": "minecraft:grass_block",
            "items": [
                "minecraft:grass_block",
                "minecraft:coarse_dirt",
                "minecraft:podzol",
                "minecraft:rooted_dirt",
                "minecraft:mud",
                "minecraft:muddy_mangrove_roots",
                "minecraft:obsidian",
                "minecraft:snow",
                "minecraft:ice",
                "minecraft:snow_block",
                "minecraft:clay",
                "minecraft:mycelium",
                "minecraft:terracotta",
                "minecraft:packed_ice",
                "minecraft:dirt_path",
                "minecraft:blue_ice"
            ]
        },
        "4e66e683-83f6-4f38-a40f-98db5672e02b": {
            "id": "4e66e683-83f6-4f38-a40f-98db5672e02b",
            "name": "Rochas",
            "icon": "minecraft:stone",
            "items": [
                "minecraft:granite",
                "minecraft:polished_granite",
                "minecraft:diorite",
                "minecraft:polished_diorite",
                "minecraft:andesite",
                "minecraft:polished_andesite",
                "minecraft:granite_wall",
                "minecraft:andesite_wall",
                "minecraft:diorite_wall",
                "minecraft:polished_granite_stairs",
                "minecraft:polished_diorite_stairs",
                "minecraft:granite_stairs",
                "minecraft:andesite_stairs",
                "minecraft:polished_andesite_stairs",
                "minecraft:diorite_stairs",
                "minecraft:polished_granite_slab",
                "minecraft:polished_diorite_slab",
                "minecraft:granite_slab",
                "minecraft:andesite_slab",
                "minecraft:polished_andesite_slab",
                "minecraft:diorite_slab"
            ]
        },
        "478891b3-5fd1-4be3-976d-fc605d5859a5": {
            "id": "478891b3-5fd1-4be3-976d-fc605d5859a5",
            "name": "Natureza",
            "icon": "minecraft:oak_leaves",
            "items": [
                "minecraft:oak_leaves",
                "minecraft:spruce_leaves",
                "minecraft:birch_leaves",
                "minecraft:jungle_leaves",
                "minecraft:acacia_leaves",
                "minecraft:dark_oak_leaves",
                "minecraft:mangrove_leaves",
                "minecraft:azalea_leaves",
                "minecraft:flowering_azalea_leaves",
                "minecraft:grass",
                "minecraft:fern",
                "minecraft:azalea",
                "minecraft:flowering_azalea",
                "minecraft:dead_bush",
                "minecraft:seagrass",
                "minecraft:dandelion",
                "minecraft:poppy",
                "minecraft:blue_orchid",
                "minecraft:allium",
                "minecraft:azure_bluet",
                "minecraft:red_tulip",
                "minecraft:orange_tulip",
                "minecraft:white_tulip",
                "minecraft:pink_tulip",
                "minecraft:oxeye_daisy",
                "minecraft:cornflower",
                "minecraft:lily_of_the_valley",
                "minecraft:wither_rose",
                "minecraft:spore_blossom",
                "minecraft:kelp",
                "minecraft:moss_carpet",
                "minecraft:moss_block",
                "minecraft:hanging_roots",
                "minecraft:big_dripleaf",
                "minecraft:small_dripleaf",
                "minecraft:vine",
                "minecraft:glow_lichen",
                "minecraft:lily_pad",
                "minecraft:sunflower",
                "minecraft:lilac",
                "minecraft:rose_bush",
                "minecraft:peony",
                "minecraft:tall_grass",
                "minecraft:large_fern"
            ]
        },
        "b96d8578-c4e5-4306-8fd5-1713efbc8203": {
            "id": "b96d8578-c4e5-4306-8fd5-1713efbc8203",
            "name": "Mangue",
            "icon": "minecraft:mangrove_log",
            "items": [
                "minecraft:mangrove_planks",
                "minecraft:mangrove_propagule",
                "minecraft:mangrove_log",
                "minecraft:mangrove_roots",
                "minecraft:stripped_mangrove_log",
                "minecraft:stripped_mangrove_wood",
                "minecraft:mangrove_wood",
                "minecraft:mangrove_slab",
                "minecraft:mangrove_fence",
                "minecraft:mangrove_stairs",
                "minecraft:mangrove_button",
                "minecraft:mangrove_pressure_plate",
                "minecraft:mangrove_door",
                "minecraft:mangrove_trapdoor",
                "minecraft:mangrove_fence_gate",
                "minecraft:mangrove_sign"
            ]
        },
        "de272c8e-8c9c-433e-80cd-e80eb64fb71a": {
            "id": "de272c8e-8c9c-433e-80cd-e80eb64fb71a",
            "name": "Redstone",
            "icon": "minecraft:piston",
            "items": [
                "minecraft:redstone",
                "minecraft:redstone_torch",
                "minecraft:redstone_block",
                "minecraft:repeater",
                "minecraft:comparator",
                "minecraft:piston",
                "minecraft:sticky_piston",
                "minecraft:slime_block",
                "minecraft:observer",
                "minecraft:hopper",
                "minecraft:dispenser",
                "minecraft:dropper",
                "minecraft:target",
                "minecraft:lever",
                "minecraft:lightning_rod",
                "minecraft:daylight_detector",
                "minecraft:sculk_sensor",
                "minecraft:tripwire_hook",
                "minecraft:trapped_chest",
                "minecraft:tnt",
                "minecraft:redstone_lamp",
                "minecraft:note_block",
                "minecraft:stone_button",
                "minecraft:polished_blackstone_button",
                "minecraft:stone_pressure_plate",
                "minecraft:polished_blackstone_pressure_plate",
                "minecraft:light_weighted_pressure_plate",
                "minecraft:heavy_weighted_pressure_plate",
                "minecraft:iron_door",
                "minecraft:iron_trapdoor",
                "minecraft:powered_rail",
                "minecraft:detector_rail",
                "minecraft:rail",
                "minecraft:activator_rail"
            ]
        },
        "7de05a9d-9881-41a1-b630-39b0483683fb": {
            "id": "7de05a9d-9881-41a1-b630-39b0483683fb",
            "name": "Oceano",
            "icon": "minecraft:sea_lantern",
            "items": [
                "minecraft:sponge",
                "minecraft:wet_sponge",
                "minecraft:sea_pickle",
                "minecraft:prismarine_slab",
                "minecraft:prismarine_brick_slab",
                "minecraft:dark_prismarine_slab",
                "minecraft:prismarine_wall",
                "minecraft:prismarine",
                "minecraft:prismarine_bricks",
                "minecraft:dark_prismarine",
                "minecraft:prismarine_stairs",
                "minecraft:prismarine_brick_stairs",
                "minecraft:dark_prismarine_stairs",
                "minecraft:sea_lantern",
                "minecraft:turtle_egg",
                "minecraft:dead_tube_coral_block",
                "minecraft:dead_brain_coral_block",
                "minecraft:dead_bubble_coral_block",
                "minecraft:dead_fire_coral_block",
                "minecraft:dead_horn_coral_block",
                "minecraft:tube_coral_block",
                "minecraft:brain_coral_block",
                "minecraft:bubble_coral_block",
                "minecraft:fire_coral_block",
                "minecraft:horn_coral_block",
                "minecraft:tube_coral",
                "minecraft:brain_coral",
                "minecraft:bubble_coral",
                "minecraft:fire_coral",
                "minecraft:horn_coral",
                "minecraft:dead_brain_coral",
                "minecraft:dead_bubble_coral",
                "minecraft:dead_fire_coral",
                "minecraft:dead_horn_coral",
                "minecraft:dead_tube_coral",
                "minecraft:tube_coral_fan",
                "minecraft:brain_coral_fan",
                "minecraft:bubble_coral_fan",
                "minecraft:fire_coral_fan",
                "minecraft:horn_coral_fan",
                "minecraft:dead_tube_coral_fan",
                "minecraft:dead_brain_coral_fan",
                "minecraft:dead_bubble_coral_fan",
                "minecraft:dead_fire_coral_fan",
                "minecraft:dead_horn_coral_fan",
                "minecraft:conduit",
                "minecraft:dried_kelp_block",
                "minecraft:dried_kelp",
                "minecraft:prismarine_shard",
                "minecraft:prismarine_crystals",
                "minecraft:nautilus_shell",
                "minecraft:heart_of_the_sea"
            ]
        },
        "7ca8fe82-922e-4075-80c6-40c5f7d95508": {
            "id": "7ca8fe82-922e-4075-80c6-40c5f7d95508",
            "name": "Comidas",
            "icon": "minecraft:pumpkin",
            "items": [
                "minecraft:apple",
                "minecraft:bread",
                "minecraft:cooked_porkchop",
                "minecraft:golden_apple",
                "minecraft:enchanted_golden_apple",
                "minecraft:cooked_cod",
                "minecraft:cooked_salmon",
                "minecraft:cookie",
                "minecraft:melon_slice",
                "minecraft:cooked_beef",
                "minecraft:cooked_chicken",
                "minecraft:baked_potato",
                "minecraft:golden_carrot",
                "minecraft:pumpkin_pie",
                "minecraft:cooked_rabbit",
                "minecraft:cooked_mutton"
            ]
        },
        "8e52afc1-be6a-4eb7-bad3-d58af9a919ca": {
            "id": "8e52afc1-be6a-4eb7-bad3-d58af9a919ca",
            "name": "Villager",
            "icon": "minecraft:smithing_table",
            "items": [
                "minecraft:crafting_table",
                "minecraft:furnace",
                "minecraft:jukebox",
                "minecraft:anvil",
                "minecraft:chipped_anvil",
                "minecraft:damaged_anvil",
                "minecraft:lectern",
                "minecraft:paper",
                "minecraft:compass",
                "minecraft:recovery_compass",
                "minecraft:clock",
                "minecraft:experience_bottle",
                "minecraft:map",
                "minecraft:loom",
                "minecraft:composter",
                "minecraft:barrel",
                "minecraft:smoker",
                "minecraft:blast_furnace",
                "minecraft:cartography_table",
                "minecraft:fletching_table",
                "minecraft:grindstone",
                "minecraft:smithing_table",
                "minecraft:stonecutter",
                "minecraft:bell"
            ]
        },
        "89cc77ba-5c1d-43db-bc10-50b0d335bd8b": {
            "id": "89cc77ba-5c1d-43db-bc10-50b0d335bd8b",
            "name": "Minério",
            "icon": "minecraft:raw_gold_block",
            "items": [
                "minecraft:coal_block",
                "minecraft:raw_iron_block",
                "minecraft:raw_gold_block",
                "minecraft:amethyst_block",
                "minecraft:iron_block",
                "minecraft:gold_block",
                "minecraft:diamond_block",
                "minecraft:netherite_block",
                "minecraft:lapis_block",
                "minecraft:emerald_block",
                "minecraft:coal",
                "minecraft:charcoal",
                "minecraft:diamond",
                "minecraft:emerald",
                "minecraft:lapis_lazuli",
                "minecraft:amethyst_shard",
                "minecraft:iron_ingot",
                "minecraft:gold_ingot",
                "minecraft:netherite_ingot",
                "minecraft:netherite_scrap",
                "minecraft:gold_nugget",
                "minecraft:iron_nugget",
                "minecraft:small_amethyst_bud",
                "minecraft:medium_amethyst_bud",
                "minecraft:large_amethyst_bud",
                "minecraft:amethyst_cluster"
            ]
        },
        "e93acff7-4c77-4bb9-9e4c-74602f49d58d": {
            "id": "e93acff7-4c77-4bb9-9e4c-74602f49d58d",
            "name": "Fortuna",
            "icon": "minecraft:diamond_ore",
            "items": [
                "minecraft:coal_ore",
                "minecraft:deepslate_coal_ore",
                "minecraft:iron_ore",
                "minecraft:deepslate_iron_ore",
                "minecraft:copper_ore",
                "minecraft:deepslate_copper_ore",
                "minecraft:gold_ore",
                "minecraft:deepslate_gold_ore",
                "minecraft:redstone_ore",
                "minecraft:deepslate_redstone_ore",
                "minecraft:emerald_ore",
                "minecraft:deepslate_emerald_ore",
                "minecraft:lapis_ore",
                "minecraft:deepslate_lapis_ore",
                "minecraft:diamond_ore",
                "minecraft:deepslate_diamond_ore",
                "minecraft:nether_gold_ore",
                "minecraft:nether_quartz_ore"
            ]
        },
        "f14b1db0-4101-442d-8286-70009f76d6b1": {
            "id": "f14b1db0-4101-442d-8286-70009f76d6b1",
            "name": "Cobre",
            "icon": "minecraft:copper_block",
            "items": [
                "minecraft:raw_copper_block",
                "minecraft:copper_block",
                "minecraft:exposed_copper",
                "minecraft:weathered_copper",
                "minecraft:oxidized_copper",
                "minecraft:cut_copper",
                "minecraft:exposed_cut_copper",
                "minecraft:weathered_cut_copper",
                "minecraft:oxidized_cut_copper",
                "minecraft:cut_copper_stairs",
                "minecraft:exposed_cut_copper_stairs",
                "minecraft:weathered_cut_copper_stairs",
                "minecraft:oxidized_cut_copper_stairs",
                "minecraft:cut_copper_slab",
                "minecraft:exposed_cut_copper_slab",
                "minecraft:weathered_cut_copper_slab",
                "minecraft:oxidized_cut_copper_slab",
                "minecraft:waxed_copper_block",
                "minecraft:waxed_exposed_copper",
                "minecraft:waxed_weathered_copper",
                "minecraft:waxed_oxidized_copper",
                "minecraft:waxed_cut_copper",
                "minecraft:waxed_exposed_cut_copper",
                "minecraft:waxed_weathered_cut_copper",
                "minecraft:waxed_oxidized_cut_copper",
                "minecraft:waxed_cut_copper_stairs",
                "minecraft:waxed_exposed_cut_copper_stairs",
                "minecraft:waxed_weathered_cut_copper_stairs",
                "minecraft:waxed_oxidized_cut_copper_stairs",
                "minecraft:waxed_cut_copper_slab",
                "minecraft:waxed_exposed_cut_copper_slab",
                "minecraft:waxed_weathered_cut_copper_slab",
                "minecraft:waxed_oxidized_cut_copper_slab",
                "minecraft:copper_ingot"
            ]
        },
        "285e6caa-2e89-4466-98ab-426151042b10": {
            "id": "285e6caa-2e89-4466-98ab-426151042b10",
            "name": "Agro",
            "icon": "minecraft:hay_block",
            "items": [
                "minecraft:brown_mushroom",
                "minecraft:red_mushroom",
                "minecraft:sugar_cane",
                "minecraft:bamboo",
                "minecraft:cactus",
                "minecraft:pumpkin",
                "minecraft:brown_mushroom_block",
                "minecraft:red_mushroom_block",
                "minecraft:mushroom_stem",
                "minecraft:melon",
                "minecraft:hay_block",
                "minecraft:wheat_seeds",
                "minecraft:wheat",
                "minecraft:cocoa_beans",
                "minecraft:pumpkin_seeds",
                "minecraft:melon_seeds",
                "minecraft:carrot",
                "minecraft:potato",
                "minecraft:beetroot",
                "minecraft:beetroot_seeds",
                "minecraft:sweet_berries",
                "minecraft:glow_berries"
            ]
        },
        "617bfb43-41f3-4545-82ed-cabc529e011e": {
            "id": "617bfb43-41f3-4545-82ed-cabc529e011e",
            "name": "Decoração",
            "icon": "minecraft:bricks",
            "items": [
                "minecraft:glass",
                "minecraft:tinted_glass",
                "minecraft:cobweb",
                "minecraft:brick_slab",
                "minecraft:mud_brick_slab",
                "minecraft:bricks",
                "minecraft:bookshelf",
                "minecraft:torch",
                "minecraft:chest",
                "minecraft:ladder",
                "minecraft:carved_pumpkin",
                "minecraft:jack_o_lantern",
                "minecraft:soul_torch",
                "minecraft:packed_mud",
                "minecraft:mud_bricks",
                "minecraft:iron_bars",
                "minecraft:chain",
                "minecraft:glass_pane",
                "minecraft:brick_stairs",
                "minecraft:mud_brick_stairs",
                "minecraft:enchanting_table",
                "minecraft:dragon_egg",
                "minecraft:ender_chest",
                "minecraft:beacon",
                "minecraft:brick_wall",
                "minecraft:mud_brick_wall",
                "minecraft:magma_block",
                "minecraft:scaffolding",
                "minecraft:painting",
                "minecraft:item_frame",
                "minecraft:glow_item_frame",
                "minecraft:flower_pot",
                "minecraft:armor_stand",
                "minecraft:end_crystal",
                "minecraft:lantern",
                "minecraft:soul_lantern",
                "minecraft:campfire",
                "minecraft:soul_campfire",
                "minecraft:lodestone",
                "minecraft:candle",
                "minecraft:ochre_froglight",
                "minecraft:verdant_froglight",
                "minecraft:pearlescent_froglight"
            ]
        },
        "f0065242-d60b-496c-b5a2-e451c2c857fa": {
            "id": "f0065242-d60b-496c-b5a2-e451c2c857fa",
            "name": "Ardósia",
            "icon": "minecraft:chiseled_deepslate",
            "items": [
                "minecraft:polished_deepslate",
                "minecraft:infested_deepslate",
                "minecraft:deepslate_bricks",
                "minecraft:cracked_deepslate_bricks",
                "minecraft:deepslate_tiles",
                "minecraft:cracked_deepslate_tiles",
                "minecraft:chiseled_deepslate",
                "minecraft:cobbled_deepslate_wall",
                "minecraft:polished_deepslate_wall",
                "minecraft:deepslate_brick_wall",
                "minecraft:deepslate_tile_wall",
                "minecraft:cobbled_deepslate_stairs",
                "minecraft:polished_deepslate_stairs",
                "minecraft:deepslate_brick_stairs",
                "minecraft:deepslate_tile_stairs",
                "minecraft:cobbled_deepslate_slab",
                "minecraft:polished_deepslate_slab",
                "minecraft:deepslate_brick_slab",
                "minecraft:deepslate_tile_slab"
            ]
        },
        "3690b6fc-c11a-4116-8bf1-f52bc272f327": {
            "id": "3690b6fc-c11a-4116-8bf1-f52bc272f327",
            "name": "Pedra",
            "icon": "minecraft:smooth_stone",
            "items": [
                "minecraft:stone_slab",
                "minecraft:smooth_stone_slab",
                "minecraft:cobblestone_slab",
                "minecraft:stone_brick_slab",
                "minecraft:smooth_stone",
                "minecraft:mossy_cobblestone",
                "minecraft:cobblestone_stairs",
                "minecraft:stone_bricks",
                "minecraft:mossy_stone_bricks",
                "minecraft:cracked_stone_bricks",
                "minecraft:chiseled_stone_bricks",
                "minecraft:stone_brick_stairs",
                "minecraft:cobblestone_wall",
                "minecraft:mossy_cobblestone_wall",
                "minecraft:mossy_stone_brick_wall",
                "minecraft:stone_brick_wall",
                "minecraft:mossy_stone_brick_stairs",
                "minecraft:mossy_cobblestone_stairs",
                "minecraft:stone_stairs",
                "minecraft:mossy_stone_brick_slab",
                "minecraft:mossy_cobblestone_slab"
            ]
        },
        "9b449de8-bc2c-469a-acce-6a120fb6b36b": {
            "id": "9b449de8-bc2c-469a-acce-6a120fb6b36b",
            "name": "Pedra Negra",
            "icon": "minecraft:blackstone",
            "items": [
                "minecraft:basalt",
                "minecraft:polished_basalt",
                "minecraft:smooth_basalt",
                "minecraft:blackstone_wall",
                "minecraft:polished_blackstone_wall",
                "minecraft:polished_blackstone_brick_wall",
                "minecraft:blackstone",
                "minecraft:blackstone_slab",
                "minecraft:blackstone_stairs",
                "minecraft:gilded_blackstone",
                "minecraft:polished_blackstone",
                "minecraft:polished_blackstone_slab",
                "minecraft:polished_blackstone_stairs",
                "minecraft:chiseled_polished_blackstone",
                "minecraft:polished_blackstone_bricks",
                "minecraft:polished_blackstone_brick_slab",
                "minecraft:polished_blackstone_brick_stairs",
                "minecraft:cracked_polished_blackstone_bricks"
            ]
        },
        "71d16866-ac06-40ae-81e2-d4e5c5c2624e": {
            "id": "71d16866-ac06-40ae-81e2-d4e5c5c2624e",
            "name": "Arenito",
            "icon": "minecraft:sandstone",
            "items": [
                "minecraft:red_sand",
                "minecraft:sandstone",
                "minecraft:chiseled_sandstone",
                "minecraft:cut_sandstone",
                "minecraft:sandstone_slab",
                "minecraft:cut_sandstone_slab",
                "minecraft:red_sandstone_slab",
                "minecraft:cut_red_sandstone_slab",
                "minecraft:smooth_red_sandstone",
                "minecraft:smooth_sandstone",
                "minecraft:sandstone_stairs",
                "minecraft:red_sandstone_wall",
                "minecraft:sandstone_wall",
                "minecraft:red_sandstone",
                "minecraft:chiseled_red_sandstone",
                "minecraft:cut_red_sandstone",
                "minecraft:red_sandstone_stairs",
                "minecraft:smooth_red_sandstone_stairs",
                "minecraft:smooth_sandstone_stairs",
                "minecraft:smooth_red_sandstone_slab",
                "minecraft:smooth_sandstone_slab"
            ]
        },
        "8ae7d8ad-0817-4e4f-9e0f-5df578daa2e9": {
            "id": "8ae7d8ad-0817-4e4f-9e0f-5df578daa2e9",
            "name": "Drops",
            "icon": "minecraft:rotten_flesh",
            "items": [
                "minecraft:arrow",
                "minecraft:string",
                "minecraft:feather",
                "minecraft:gunpowder",
                "minecraft:leather",
                "minecraft:slime_ball",
                "minecraft:egg",
                "minecraft:ink_sac",
                "minecraft:glow_ink_sac",
                "minecraft:bone",
                "minecraft:rotten_flesh",
                "minecraft:ender_pearl",
                "minecraft:blaze_rod",
                "minecraft:skeleton_skull",
                "minecraft:wither_skeleton_skull",
                "minecraft:zombie_head",
                "minecraft:creeper_head",
                "minecraft:dragon_head",
                "minecraft:nether_star",
                "minecraft:rabbit_foot",
                "minecraft:rabbit_hide",
                "minecraft:shulker_shell",
                "minecraft:phantom_membrane"
            ]
        },
        "aa768d8f-0fb7-4fd3-88bd-76d840744f87": {
            "id": "aa768d8f-0fb7-4fd3-88bd-76d840744f87",
            "name": "Poções",
            "icon": "minecraft:potion",
            "items": [
                "minecraft:pufferfish",
                "minecraft:ghast_tear",
                "minecraft:nether_wart",
                "minecraft:glass_bottle",
                "minecraft:spider_eye",
                "minecraft:fermented_spider_eye",
                "minecraft:blaze_powder",
                "minecraft:magma_cream",
                "minecraft:brewing_stand",
                "minecraft:cauldron",
                "minecraft:glistering_melon_slice",
                "minecraft:dragon_breath",
                "minecraft:spectral_arrow",
                "minecraft:tipped_arrow"
            ]
        },
        "92adf20e-5a21-495e-9774-fa2d2b330d4f": {
            "id": "92adf20e-5a21-495e-9774-fa2d2b330d4f",
            "name": "Nether",
            "icon": "minecraft:soul_sand",
            "items": [
                "minecraft:nether_brick_slab",
                "minecraft:soul_sand",
                "minecraft:soul_soil",
                "minecraft:glowstone",
                "minecraft:nether_bricks",
                "minecraft:cracked_nether_bricks",
                "minecraft:chiseled_nether_bricks",
                "minecraft:nether_brick_fence",
                "minecraft:nether_brick_stairs",
                "minecraft:nether_brick_wall",
                "minecraft:red_nether_brick_wall",
                "minecraft:red_nether_bricks",
                "minecraft:red_nether_brick_stairs",
                "minecraft:red_nether_brick_slab",
                "minecraft:glowstone_dust",
                "minecraft:nether_brick",
                "minecraft:shroomlight",
                "minecraft:crying_obsidian",
                "minecraft:respawn_anchor"
            ]
        },
        "6c88df3d-08d6-4f52-b05a-bdb9153d5d03": {
            "id": "6c88df3d-08d6-4f52-b05a-bdb9153d5d03",
            "name": "Nether Carmesim",
            "icon": "minecraft:crimson_nylium",
            "items": [
                "minecraft:crimson_nylium",
                "minecraft:crimson_planks",
                "minecraft:crimson_stem",
                "minecraft:stripped_crimson_stem",
                "minecraft:stripped_crimson_hyphae",
                "minecraft:crimson_hyphae",
                "minecraft:crimson_fungus",
                "minecraft:crimson_roots",
                "minecraft:weeping_vines",
                "minecraft:crimson_slab",
                "minecraft:crimson_fence",
                "minecraft:crimson_stairs",
                "minecraft:nether_wart_block",
                "minecraft:crimson_button",
                "minecraft:crimson_pressure_plate",
                "minecraft:crimson_door",
                "minecraft:crimson_trapdoor",
                "minecraft:crimson_fence_gate",
                "minecraft:crimson_sign"
            ]
        },
        "b8758b7e-8cc1-441c-b70f-5eca8eeba82e": {
            "id": "b8758b7e-8cc1-441c-b70f-5eca8eeba82e",
            "name": "Nether Distorcido",
            "icon": "minecraft:warped_nylium",
            "items": [
                "minecraft:warped_nylium",
                "minecraft:warped_planks",
                "minecraft:warped_stem",
                "minecraft:stripped_warped_stem",
                "minecraft:stripped_warped_hyphae",
                "minecraft:warped_hyphae",
                "minecraft:warped_fungus",
                "minecraft:warped_roots",
                "minecraft:nether_sprouts",
                "minecraft:twisting_vines",
                "minecraft:warped_slab",
                "minecraft:warped_fence",
                "minecraft:warped_stairs",
                "minecraft:warped_wart_block",
                "minecraft:warped_button",
                "minecraft:warped_pressure_plate",
                "minecraft:warped_door",
                "minecraft:warped_trapdoor",
                "minecraft:warped_fence_gate",
                "minecraft:warped_sign"
            ]
        },
        "49cce929-edf9-4514-a0e8-76a53bd63832": {
            "id": "49cce929-edf9-4514-a0e8-76a53bd63832",
            "name": "Quartzo",
            "icon": "minecraft:quartz_block",
            "items": [
                "minecraft:quartz_slab",
                "minecraft:smooth_quartz",
                "minecraft:chiseled_quartz_block",
                "minecraft:quartz_block",
                "minecraft:quartz_bricks",
                "minecraft:quartz_pillar",
                "minecraft:quartz_stairs",
                "minecraft:smooth_quartz_stairs",
                "minecraft:smooth_quartz_slab",
                "minecraft:quartz"
            ]
        },
        "2bd68bc3-fbd3-45b0-9a9c-c7b202cd1c37": {
            "id": "2bd68bc3-fbd3-45b0-9a9c-c7b202cd1c37",
            "name": "Miscelânea",
            "icon": "minecraft:book",
            "items": [
                "minecraft:bone_block",
                "minecraft:scute",
                "minecraft:stick",
                "minecraft:bowl",
                "minecraft:flint",
                "minecraft:bucket",
                "minecraft:snowball",
                "minecraft:brick",
                "minecraft:clay_ball",
                "minecraft:book",
                "minecraft:bone_meal",
                "minecraft:sugar",
                "minecraft:ender_eye",
                "minecraft:fire_charge",
                "minecraft:written_book",
                "minecraft:poisonous_potato",
                "minecraft:lead",
                "minecraft:name_tag",
                "minecraft:disc_fragment_5",
                "minecraft:echo_shard"
            ]
        },
        "14a50539-4eb2-4ba7-be5b-37d1d06ca5cf": {
            "id": "14a50539-4eb2-4ba7-be5b-37d1d06ca5cf",
            "name": "Foguetes",
            "icon": "minecraft:firework_rocket",
            "items": [
                "minecraft:firework_rocket",
                "minecraft:firework_star"
            ]
        },
        "87368321-c424-40b3-a789-e4d05df8d757": {
            "id": "87368321-c424-40b3-a789-e4d05df8d757",
            "name": "O Fim",
            "icon": "minecraft:end_stone",
            "items": [
                "minecraft:purpur_slab",
                "minecraft:end_rod",
                "minecraft:chorus_flower",
                "minecraft:purpur_block",
                "minecraft:purpur_pillar",
                "minecraft:purpur_stairs",
                "minecraft:end_stone",
                "minecraft:end_stone_bricks",
                "minecraft:end_stone_brick_wall",
                "minecraft:end_stone_brick_stairs",
                "minecraft:end_stone_brick_slab",
                "minecraft:popped_chorus_fruit"
            ]
        },
        "ea1cfe0c-958f-4678-b9bb-95ffa092d344": {
            "id": "ea1cfe0c-958f-4678-b9bb-95ffa092d344",
            "name": "Apiário",
            "icon": "minecraft:honeycomb",
            "items": [
                "minecraft:honey_block",
                "minecraft:honeycomb",
                "minecraft:bee_nest",
                "minecraft:beehive",
                "minecraft:honey_bottle",
                "minecraft:honeycomb_block"
            ]
        },
        "4dce6044-ffbd-4f59-8467-f34e28c66868": {
            "id": "4dce6044-ffbd-4f59-8467-f34e28c66868",
            "name": "Subterrâneo",
            "icon": "minecraft:dripstone_block",
            "items": [
                "minecraft:calcite",
                "minecraft:tuff",
                "minecraft:dripstone_block",
                "minecraft:sculk",
                "minecraft:sculk_vein",
                "minecraft:sculk_catalyst",
                "minecraft:sculk_shrieker",
                "minecraft:pointed_dripstone"
            ]
        }
    },
    categories_order: [
        "7ca8fe82-922e-4075-80c6-40c5f7d95508",
        "14a50539-4eb2-4ba7-be5b-37d1d06ca5cf",
        "89cc77ba-5c1d-43db-bc10-50b0d335bd8b",
        "e93acff7-4c77-4bb9-9e4c-74602f49d58d",
        "0ddccd36-039c-47c8-9c61-bb2ff992374d",
        "3690b6fc-c11a-4116-8bf1-f52bc272f327",
        "4e66e683-83f6-4f38-a40f-98db5672e02b",
        "f0065242-d60b-496c-b5a2-e451c2c857fa",
        "9b449de8-bc2c-469a-acce-6a120fb6b36b",
        "4dce6044-ffbd-4f59-8467-f34e28c66868",
        "de272c8e-8c9c-433e-80cd-e80eb64fb71a",
        "285e6caa-2e89-4466-98ab-426151042b10",
        "478891b3-5fd1-4be3-976d-fc605d5859a5",
        "8e52afc1-be6a-4eb7-bad3-d58af9a919ca",
        "8ae7d8ad-0817-4e4f-9e0f-5df578daa2e9",
        "2bd68bc3-fbd3-45b0-9a9c-c7b202cd1c37",
        "aa768d8f-0fb7-4fd3-88bd-76d840744f87",
        "a6f059e2-518b-452b-9759-ef159770897c",
        "f732878d-732b-4e0b-9221-05e4546a5df0",
        "5feeb9a0-0d40-4874-be24-d9f3ec0fed9b",
        "f1483c72-6100-4e5d-aca2-1f6c6361413e",
        "5aae41cc-8854-49c2-9c86-0e028dd1b77e",
        "f8b8e062-3bc7-4e0a-87df-7381747acea6",
        "b96d8578-c4e5-4306-8fd5-1713efbc8203",
        "617bfb43-41f3-4545-82ed-cabc529e011e",
        "49cce929-edf9-4514-a0e8-76a53bd63832",
        "71d16866-ac06-40ae-81e2-d4e5c5c2624e",
        "f14b1db0-4101-442d-8286-70009f76d6b1",
        "7de05a9d-9881-41a1-b630-39b0483683fb",
        "f495d4f1-29c5-48cf-b5ec-c8a425721cca",
        "f95e86b5-6f38-423b-ba0c-b9baedd4bad4",
        "22f356d9-2663-4b42-8272-5b420ac33f9e",
        "58ab7a27-7dd7-4b59-b83a-d99bb53c0bfb",
        "62b00652-c44d-4b4a-9d64-ba8ec84780e1",
        "6a2e8ac3-4f29-4786-a78b-fce2af534f25",
        "9aaf491d-b6a6-40c1-9826-c476bb607666",
        "c8945d8c-d581-43d6-b3fa-63e842b84ccd",
        "a546a45e-5406-498a-b0b6-d2fafc299b48",
        "76684468-0636-4849-87e3-95249325676b",
        "d16460a0-e0ab-46b7-899a-aa5667ffc7a1",
        "f397a635-9c1d-4f19-81e4-e205f82c3d69",
        "30a06635-89c3-46fe-bd94-a69cad118ffb",
        "70415771-b8d1-4011-ad2b-5749ee1c2711",
        "e87e8418-20e3-4a73-8335-fead03da5404",
        "2d2b8913-405e-41a5-b24c-995095e6e32c",
        "87368321-c424-40b3-a789-e4d05df8d757",
        "92adf20e-5a21-495e-9774-fa2d2b330d4f",
        "b8758b7e-8cc1-441c-b70f-5eca8eeba82e",
        "6c88df3d-08d6-4f52-b05a-bdb9153d5d03",
        "536ba551-b256-4a68-bbb8-26e42d4f3115",
        "c4945c01-8926-4737-a149-f3b83e6881a4",
        "ea1cfe0c-958f-4678-b9bb-95ffa092d344",
        "26b8ca6b-c979-476a-a6e1-76954ef3d95f",
        "7b5f1570-b945-49ba-aaed-4a61a82edd79"
    ]
}

export default Preset;